- name: Add yarn signing key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add yarn repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present

- name: Update cache
  apt:
    update_cache: yes

- name: Update packages
  apt:
    upgrade: safe

- name: Install OS packages
  apt:
    name:
      - snapd
      - aptitude
      - vim
      - tree
      - mc
      - git
      - git-review
      - gitk
      - meld
      - python3
      - python3-pip
      - python3-venv
      - libreoffice
      - keepassxc
      - gimp
      - guake
      - libutempter0  # Fixes guake 3.0.5 issue
      - nodejs
      - npm
      - xserver-xorg-input-synaptics
      - xserver-xorg-video-vesa
      - xserver-xorg-video-ati
      - xserver-xorg-video-intel
      - xserver-xorg-video-nouveau
      - python3-gdal
      - gdal-bin
      - tig
      - tmux

- name: Install yarn, without system node
  apt:
    name: yarn
    install_recommends: no

- name: install pycharm from snap
  command: snap install pycharm-community --classic

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
